/**
 * Typed accessors over the bundled MTA static data (src/data/static-data.json,
 * generated by scripts/generate-static.ts from the MTA GTFS static feed).
 */

import staticJson from './data/static-data.json';

export interface StaticRoute {
  /** GTFS route_long_name, e.g. "8 Avenue Express" */
  name: string;
  /** GTFS route_short_name; the three shuttles all share "S" */
  shortName: string;
  /** Official MTA line color, no leading '#', e.g. "0039A6" */
  color: string;
  textColor: string;
}

export interface StaticStation {
  id: string;
  name: string;
  /** Route ids serving this station, ordered by the MTA's official route sort order */
  routes: string[];
  /** Platform stop ids per direction; realtime stop_time_updates match these ids */
  platforms: { N: string; S: string };
}

export type Direction = 'N' | 'S';

interface StaticData {
  sourceUrl: string;
  generatedAt: string;
  routes: Record<string, StaticRoute>;
  stations: StaticStation[];
  headsigns: {
    trips: Record<string, string>;
    byRoute: Record<string, { N: string; S: string }>;
  };
}

// generated JSON: shape is fixed by the generator, not by tsc's literal inference
const data = staticJson as unknown as StaticData;

const stationById = new Map(data.stations.map((s) => [s.id, s]));

export function allStations(): StaticStation[] {
  return data.stations;
}

export function getStationById(id: string): StaticStation | undefined {
  return stationById.get(id);
}

export function getRoute(routeId: string): StaticRoute | undefined {
  return data.routes[routeId];
}

/** Routes serving a station, with color info, in the MTA's official sort order. */
export function routesForStation(stationId: string): StaticRoute[] {
  const station = getStationById(stationId);
  if (!station) return [];
  return station.routes.map((id) => data.routes[id]).filter((r) => r !== undefined);
}

export function platformForDirection(station: StaticStation, direction: Direction): string {
  return station.platforms[direction];
}

function normalizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

/**
 * Station name search for the companion settings picker: exact match first,
 * then whole-word prefix matches, then substring matches.
 */
export function findStationsByName(query: string): StaticStation[] {
  const q = normalizeName(query);
  if (!q) return [];
  const scored: Array<{ station: StaticStation; score: number }> = [];
  for (const station of data.stations) {
    const name = normalizeName(station.name);
    let score: number | null = null;
    if (name === q) score = 0;
    else if (name.split(' ').some((w) => w.startsWith(q))) score = 1;
    else if (name.includes(q)) score = 2;
    if (score !== null) scored.push({ station, score });
  }
  return scored
    .sort((a, b) => a.score - b.score || (a.station.name < b.station.name ? -1 : 1))
    .slice(0, 20)
    .map((s) => s.station);
}

/**
 * Headsign for a GTFS-Realtime trip id. Realtime trip ids are the static trip
 * id after the last underscore, but both forms resolve. When the trip is not
 * in the bundle (feed data drift, unknown trip), falls back to the route's
 * most common headsign for the given direction.
 */
export function headsignForTrip(
  tripId: string,
  fallback?: { routeId?: string; direction?: Direction },
): string | undefined {
  const headsign = data.headsigns.trips[tripId] ?? data.headsigns.trips[tripId.split('_').pop() ?? ''];
  if (headsign) return headsign;

  const byRoute = fallback?.routeId ? data.headsigns.byRoute[fallback.routeId] : undefined;
  if (!byRoute) return undefined;
  if (fallback?.direction) {
    const directed = byRoute[fallback.direction];
    if (directed) return directed;
  }
  return byRoute.N || byRoute.S || undefined;
}

export const staticDataSource = data.sourceUrl;
export const staticDataGeneratedAt = data.generatedAt;
